#### Functional Programming

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./Top5000.csv')

In [3]:
df.head(2)

,Unnamed: 0,ars_name,rel_date,gens,descs,avg_rat,num_rat,num_revs,album,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,duration_ms,time_signature
0,0,Radiohead,16 June 1997,"Alternative Rock, Art Rock","melancholic, anxious, futuristic, alienation, ...",4.23,"70,382",1531,OK Computer,0.135763,0.288083,0.565917,0.161053,0.159375,-9.102417,0.056308,115.45075,0.291733,268435.5,4.0
1,1,Pink Floyd,12 September 1975,"Progressive Rock, Art Rock","melancholic, atmospheric, progressive, male vo...",4.29,"48,662",983,Wish You Were Here,0.602800,0.373600,0.409800,0.363040,0.384940,-12.689400,0.039740,130.01880,0.259040,530512.0,3.6

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4402 entries, 0 to 4401
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        4402 non-null   int64
 1   ars_name          4402 non-null   object
 2   rel_date          4402 non-null   object
 3   gens              4402 non-null   object
 4   descs             4304 non-null   object
 5   avg_rat           4402 non-null   float64
 6   num_rat           4402 non-null   object
 7   num_revs          4402 non-null   int64
 8   album             4402 non-null   object
 9   acousticness      4402 non-null   float64
 10  danceability      4402 non-null   float64
 11  energy            4402 non-null   float64
 12  instrumentalness  4402 non-null   float64
 13  liveness          4402 non-null   float64
 14  loudness          4402 non-null   float64
 15  speechiness       4402 non-null   float64
 16  tempo             4402 non-null   float64
 17  valence           4402 non-null   float64
 18  duration_ms       4402 non-null   float64
 19  time_signature    4402 non-null   float64
dtypes: float64(12), int64(2), object(6)
memory usage: 687.9+ KB

In [5]:
df.columns

Index(['Unnamed: 0', 'ars_name', 'rel_date', 'gens', 'descs', 'avg_rat',
       'num_rat', 'num_revs', 'album', 'acousticness', 'danceability',
       'energy', 'instrumentalness', 'liveness', 'loudness', 'speechiness',
       'tempo', 'valence', 'duration_ms', 'time_signature'],
      dtype='object')

In [6]:
df = df[['ars_name', 'album', 'avg_rat', 'rel_date', 'gens', 'duration_ms']]
df

,ars_name,album,avg_rat,rel_date,gens,duration_ms
0,Radiohead,OK Computer,4.23,16 June 1997,"Alternative Rock, Art Rock",268435.500000
1,Pink Floyd,Wish You Were Here,4.29,12 September 1975,"Progressive Rock, Art Rock",530512.000000
2,King Crimson,In the Court of the Crimson King,4.30,10 October 1969,"Progressive Rock, Art Rock",507644.125000
3,Radiohead,Kid A,4.21,3 October 2000,"Art Rock, Experimental Rock, Electronic",325379.529412
4,Kendrick Lamar,To Pimp a Butterfly,4.27,15 March 2015,"Conscious Hip Hop, West Coast Hip Hop, Jazz Rap",296225.750000
...,...,...,...,...,...,...
4397,John Hiatt,Bring the Family,3.68,May 1987,"Singer/Songwriter, Roots Rock, Americana",273146.700000
4398,Catharsis,Passion,3.65,1999,"Crust Punk, Metalcore",202675.450000
4399,Gracious,Gracious!,3.69,17 July 1970,"Progressive Rock, Symphonic Prog",193269.454545
4400,And Also the Trees,(Listen For) The Rag and Bone Man,3.68,12 November 2007,Art Rock,229115.846154
4401,Minnie Riperton,Adventures in Paradise,3.69,22 May 1975,"Smooth Soul, Pop Soul",242398.800000

In [7]:
df.head(2)

,ars_name,album,avg_rat,rel_date,gens,duration_ms
0,Radiohead,OK Computer,4.23,16 June 1997,"Alternative Rock, Art Rock",268435.5
1,Pink Floyd,Wish You Were Here,4.29,12 September 1975,"Progressive Rock, Art Rock",530512.0

In [8]:
df1 = df.sort_values(by='avg_rat', ascending=False)
df1

,ars_name,album,avg_rat,rel_date,gens,duration_ms
13,Mingus,The Black Saint and the Sinner Lady,4.34,July 1963,"Avant-Garde Jazz, Third Stream",591406.750000
2,King Crimson,In the Court of the Crimson King,4.30,10 October 1969,"Progressive Rock, Art Rock",507644.125000
15,John Coltrane,A Love Supreme,4.30,February 1965,Spiritual Jazz,491530.250000
1,Pink Floyd,Wish You Were Here,4.29,12 September 1975,"Progressive Rock, Art Rock",530512.000000
4,Kendrick Lamar,To Pimp a Butterfly,4.27,15 March 2015,"Conscious Hip Hop, West Coast Hip Hop, Jazz Rap",296225.750000
...,...,...,...,...,...,...
4360,Brockhampton,Saturation,3.55,9 June 2017,"Pop Rap, West Coast Hip Hop",185479.266667
3775,AC/DC,Back in Black,3.54,18 August 1980,Hard Rock,252812.000000
3354,Kanye West,808s & Heartbreak,3.54,24 November 2008,"Electropop, Synthpop",260431.083333
3894,Kendrick Lamar,Damn.,3.52,14 April 2017,"West Coast Hip Hop, Conscious Hip Hop",235783.785714
3898,Guns n' Roses,Appetite for Destruction,3.52,21 July 1987,Hard Rock,268846.583333

In [9]:
df1['duration_ms'] = pd.to_timedelta(df1['duration_ms'], unit='ms')
df1

,ars_name,album,avg_rat,rel_date,gens,duration_ms
13,Mingus,The Black Saint and the Sinner Lady,4.34,July 1963,"Avant-Garde Jazz, Third Stream",0 days 00:09:51.406750
2,King Crimson,In the Court of the Crimson King,4.30,10 October 1969,"Progressive Rock, Art Rock",0 days 00:08:27.644125
15,John Coltrane,A Love Supreme,4.30,February 1965,Spiritual Jazz,0 days 00:08:11.530250
1,Pink Floyd,Wish You Were Here,4.29,12 September 1975,"Progressive Rock, Art Rock",0 days 00:08:50.512000
4,Kendrick Lamar,To Pimp a Butterfly,4.27,15 March 2015,"Conscious Hip Hop, West Coast Hip Hop, Jazz Rap",0 days 00:04:56.225750
...,...,...,...,...,...,...
4360,Brockhampton,Saturation,3.55,9 June 2017,"Pop Rap, West Coast Hip Hop",0 days 00:03:05.479266667
3775,AC/DC,Back in Black,3.54,18 August 1980,Hard Rock,0 days 00:04:12.812000
3354,Kanye West,808s & Heartbreak,3.54,24 November 2008,"Electropop, Synthpop",0 days 00:04:20.431083333
3894,Kendrick Lamar,Damn.,3.52,14 April 2017,"West Coast Hip Hop, Conscious Hip Hop",0 days 00:03:55.783785714
3898,Guns n' Roses,Appetite for Destruction,3.52,21 July 1987,Hard Rock,0 days 00:04:28.846583333

In [10]:
len(df1['gens'].unique())

1938

In [14]:
def main_genre(genres):
    try:
        return genres.split(',')[0].strip()
    except:
        return 'no_genre'

In [15]:
df1['gens'] = df1['gens'].apply(main_genre)
df1

,ars_name,album,avg_rat,rel_date,gens,duration_ms
13,Mingus,The Black Saint and the Sinner Lady,4.34,July 1963,Avant-Garde Jazz,0 days 00:09:51.406750
2,King Crimson,In the Court of the Crimson King,4.30,10 October 1969,Progressive Rock,0 days 00:08:27.644125
15,John Coltrane,A Love Supreme,4.30,February 1965,Spiritual Jazz,0 days 00:08:11.530250
1,Pink Floyd,Wish You Were Here,4.29,12 September 1975,Progressive Rock,0 days 00:08:50.512000
4,Kendrick Lamar,To Pimp a Butterfly,4.27,15 March 2015,Conscious Hip Hop,0 days 00:04:56.225750
...,...,...,...,...,...,...
4360,Brockhampton,Saturation,3.55,9 June 2017,Pop Rap,0 days 00:03:05.479266667
3775,AC/DC,Back in Black,3.54,18 August 1980,Hard Rock,0 days 00:04:12.812000
3354,Kanye West,808s & Heartbreak,3.54,24 November 2008,Electropop,0 days 00:04:20.431083333
3894,Kendrick Lamar,Damn.,3.52,14 April 2017,West Coast Hip Hop,0 days 00:03:55.783785714
3898,Guns n' Roses,Appetite for Destruction,3.52,21 July 1987,Hard Rock,0 days 00:04:28.846583333

In [16]:
len(df1['gens'].unique())

428

In [18]:
df_gens = df1[df1['gens'] == 'Hard Rock']
df_gens

,ars_name,album,avg_rat,rel_date,gens,duration_ms
35,Led Zeppelin,Led Zeppelin [IV],4.10,8 November 1971,Hard Rock,0 days 00:05:11.886000
169,The Who,Who's Next,3.96,25 August 1971,Hard Rock,0 days 00:05:18.482827586
123,Led Zeppelin,Led Zeppelin,3.95,12 January 1969,Hard Rock,0 days 00:05:11.886000
203,Led Zeppelin,Physical Graffiti,3.94,24 February 1975,Hard Rock,0 days 00:05:39.368636364
149,Led Zeppelin,Led Zeppelin II,3.94,22 October 1969,Hard Rock,0 days 00:04:18.844000
...,...,...,...,...,...,...
3324,Boston,Boston,3.63,25 August 1976,Hard Rock,0 days 00:04:43.051750
4347,Whitesnake,Whitesnake,3.62,7 April 1987,Hard Rock,0 days 00:04:49.069000
2701,AC/DC,Highway to Hell,3.61,27 July 1979,Hard Rock,0 days 00:04:10.040100
3775,AC/DC,Back in Black,3.54,18 August 1980,Hard Rock,0 days 00:04:12.812000
3898,Guns n' Roses,Appetite for Destruction,3.52,21 July 1987,Hard Rock,0 days 00:04:28.846583333

---

In [23]:
# Pipeline secuencial

df = pd.read_csv('./Top5000.csv')
df = df[['ars_name', 'album', 'avg_rat', 'rel_date', 'gens', 'duration_ms']]
df = df.sort_values(by='avg_rat', ascending=False)
df['duration_ms'] = pd.to_timedelta(df['duration_ms'], unit='ms')
df['gens'] = df['gens'].apply(main_genre)
df = df[df['gens'] == 'Hard Rock']
df = df.reset_index().drop(['index'], axis = 1)
df

,ars_name,album,avg_rat,rel_date,gens,duration_ms
0,Led Zeppelin,Led Zeppelin [IV],4.10,8 November 1971,Hard Rock,0 days 00:05:11.886000
1,The Who,Who's Next,3.96,25 August 1971,Hard Rock,0 days 00:05:18.482827586
2,Led Zeppelin,Led Zeppelin,3.95,12 January 1969,Hard Rock,0 days 00:05:11.886000
3,Led Zeppelin,Physical Graffiti,3.94,24 February 1975,Hard Rock,0 days 00:05:39.368636364
4,Led Zeppelin,Led Zeppelin II,3.94,22 October 1969,Hard Rock,0 days 00:04:18.844000
...,...,...,...,...,...,...
99,Boston,Boston,3.63,25 August 1976,Hard Rock,0 days 00:04:43.051750
100,Whitesnake,Whitesnake,3.62,7 April 1987,Hard Rock,0 days 00:04:49.069000
101,AC/DC,Highway to Hell,3.61,27 July 1979,Hard Rock,0 days 00:04:10.040100
102,AC/DC,Back in Black,3.54,18 August 1980,Hard Rock,0 days 00:04:12.812000
103,Guns n' Roses,Appetite for Destruction,3.52,21 July 1987,Hard Rock,0 days 00:04:28.846583333

In [24]:
# Pipeline funcional

def funcion_guarra():
    df = pd.read_csv('./Top5000.csv')   # Funcion para importar datos
    df = df[['ars_name', 'album', 'avg_rat', 'rel_date', 'gens', 'duration_ms']] # Funcion para seleccionar columnas
    df = df.sort_values(by='avg_rat', ascending=False) # Funcion para ordenar datos
    df['duration_ms'] = pd.to_timedelta(df['duration_ms'], unit='ms') # Funcion limpiar datos
    df['gens'] = df['gens'].apply(main_genre) # Funcion para limpiar datos
    df = df[df['gens'] == 'Hard Rock'] # Funcion para seleccionar datos
    df = df.reset_index().drop(['index'], axis = 1)
    return df

In [25]:
funcion_guarra()

,ars_name,album,avg_rat,rel_date,gens,duration_ms
0,Led Zeppelin,Led Zeppelin [IV],4.10,8 November 1971,Hard Rock,0 days 00:05:11.886000
1,The Who,Who's Next,3.96,25 August 1971,Hard Rock,0 days 00:05:18.482827586
2,Led Zeppelin,Led Zeppelin,3.95,12 January 1969,Hard Rock,0 days 00:05:11.886000
3,Led Zeppelin,Physical Graffiti,3.94,24 February 1975,Hard Rock,0 days 00:05:39.368636364
4,Led Zeppelin,Led Zeppelin II,3.94,22 October 1969,Hard Rock,0 days 00:04:18.844000
...,...,...,...,...,...,...
99,Boston,Boston,3.63,25 August 1976,Hard Rock,0 days 00:04:43.051750
100,Whitesnake,Whitesnake,3.62,7 April 1987,Hard Rock,0 days 00:04:49.069000
101,AC/DC,Highway to Hell,3.61,27 July 1979,Hard Rock,0 days 00:04:10.040100
102,AC/DC,Back in Black,3.54,18 August 1980,Hard Rock,0 days 00:04:12.812000
103,Guns n' Roses,Appetite for Destruction,3.52,21 July 1987,Hard Rock,0 days 00:04:28.846583333

In [26]:
#Modulo acq

def acquisition(path):
    try:
        df = pd.read_csv(path)
        return df
    except:
        'No data'

In [27]:
# Modulo Pepe

def col_select(df, cols):
    df = df[cols]
    return df

In [29]:
def sort_df(df, col, order):
    # col = string, order = True/False
    df = df.sort_values(by=col, ascending=order).reset_index(drop=True)
    return df

In [30]:
def delta_time(df, col_input, col_output='delta_time', unit='ms'):
    df[col_output] = pd.to_timedelta(df[col_input], unit=unit)
    return df

In [31]:
def main_genre(genres):
    try:
        return genres.split(',')[0].strip()
    except:
        return 'no_genre'

In [32]:
def genre_selector(df, col_input='gens', col_output='single_genre'):
    df[col_output] = df[col_input].apply(main_genre)
    return df

In [35]:
def genre_filter(df, col, genre):
    if genre in list(df[col].unique()):
        df = df[df[col] == genre].reset_index(drop=True)
        return df
    else:
        return 'No correct genre selected'

In [38]:
path1 = './Top5000.csv'
cols1 = ['ars_name', 'album', 'avg_rat', 'rel_date', 'gens', 'duration_ms']
col1 = 'avg_rat'
order1 = True
col_input1 = 'duration_ms'
col2 = 'gens'
genre1 = 'Hard Rock'
col3 = 'duration_ms'
order2 = True

df1 = acquisition(path1)
df2 = col_select(df1, cols1)
df3 = sort_df(df2, col1, order1)
df4 = delta_time(df3, col_input1)
df5 = genre_selector(df4, col_output='gens')
df6 = genre_filter(df5, col2, genre1)
df7 = sort_df(df6, col3, order2)
df7

,ars_name,album,avg_rat,rel_date,gens,duration_ms,delta_time
0,Three Man Army,A Third of a Lifetime,3.70,1971,Hard Rock,73297.000000,0 days 00:01:13.297000
1,Wishbone Ash,Argus,3.86,28 April 1972,Hard Rock,105605.428571,0 days 00:01:45.605428571
2,Budgie,Bandolier,3.71,September 1975,Hard Rock,118962.000000,0 days 00:01:58.962000
3,Uriah Heep,Look at Yourself,3.82,October 1971,Hard Rock,145615.384615,0 days 00:02:25.615384615
4,Gun,Gun,3.70,May 1969,Hard Rock,148486.000000,0 days 00:02:28.486000
...,...,...,...,...,...,...,...
99,Grand Funk Railroad,On Time,3.70,25 August 1969,Hard Rock,346814.170213,0 days 00:05:46.814170213
100,Deep Purple,Deep Purple in Rock,3.91,3 June 1970,Hard Rock,362013.285714,0 days 00:06:02.013285714
101,Uriah Heep,Salisbury,3.77,February 1971,Hard Rock,383372.136364,0 days 00:06:23.372136364
102,Wishbone Ash,Wishbone Ash,3.76,4 December 1970,Hard Rock,422046.833333,0 days 00:07:02.046833333
103,Golden Earring,Moontan,3.76,September 1973,Hard Rock,477898.600000,0 days 00:07:57.898600